# kubernetes/influxdb/influxdb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: capiot-app
spec:
  selector:
    app: influxdb
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: tcp
      protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP