@startuml
' Set left to right direction for overall layout
left to right direction

skinparam componentStyle uml2
skinparam nodePadding 20
skinparam componentPadding 5
skinparam classAttributeIconSize 0
skinparam nodeMargin 50
skinparam padding 5
skinparam lineThickness 1
skinparam backgroundColor #EEEBD

' Nodes and components
node "Client" {
  component "FrontEnd (Web/Mobile)" as FE
}

cloud "Auth0 (Token Provider)" as Auth0{

}

node "Google VPS Provider" {
  component "API Backend" as API_Backend
  component "WebSocket Server" as WS_Server

  node "Databases" {
    database "MongoDB (User/Site Data)" as MongoDB
  }
}

' Fleet of STM32s node placed explicitly to the right of "API InfluxDB"
node "Fleet of STM32s" {
  component "STM32 Device" as STM32
}

' Relationships
FE -> Auth0 : "Tok/Req"
FE ---> API_Backend : "Set/Update Functioning Range"
API_Backend -down-> Auth0 : "Tok/Verif"
API_Backend --> MongoDB : "Store/Retrieve Data"

API_Backend ---> WS_Server : "Send Functioning Range Update"
STM32 ---> WS_Server : "Receive Functioning Range"
STM32 -> Auth0 : "Tok/Req"

' Add notes for better understanding
note right of API_Backend
  1. Token Verification with Auth0
  2. Retrieves & Stores Operation Data
  3. Sends Functioning Range to WebSocket Server
end note

note right of STM32
  1. Receives Functioning Range Updates via WebSocket
  2. Applies the Range for Operation
end note

' Note for the relationship between API Backend and STM32 Device
note left of API_Backend
  1. WebSocket or API Polling
  2. Sends Functioning Range Information
end note

@enduml
