apiVersion: v1
kind: Service
metadata:
  name: api-influxdb-service
  namespace: capiot
  labels:
    app: capiot-influxdb-api
spec:
  type: NodePort
  selector:
    app: capiot-influxdb-api
  ports:
    - protocol: TCP
      port: 80       # Port interne du service
      targetPort: 8000  # Port sur le pod
      nodePort: 30082   # Choisis un NodePort unique dans la plage 30000-32767
