apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-influxdb-deployment
  namespace: capiot
  labels:
    app: capiot-influxdb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capiot-influxdb-api
  template:
    metadata:
      labels:
        app: capiot-influxdb-api
    spec:
      containers:
        - name: capiot-influxdb-api
          image: flamware/capiot-influxdb-api:20251026135033-e744d627
          ports:
            - containerPort: 8000 # IMPORTANT: Verify your API listens on this port
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-influxdb-config
                  key: API_URL
            - name: INFLUXDB_URL
              value: "http://influxdb-service.capiot.svc.cluster.local:8086"
            - name: INFLUXDB_ORG
              valueFrom:
                secretKeyRef:
                  name: influxdb-creds # <-- CORRECTED: This is the actual secret name
                  key: INFLUXDB_ORG
            - name: INFLUXDB_BUCKET # <-- Added this back as it's needed for the API
              valueFrom:
                secretKeyRef:
                  name: influxdb-creds # <-- CORRECTED: This is the actual secret name
                  key: INFLUXDB_BUCKET
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-creds # <-- CORRECTED: This is the actual secret name for admin creds
                  key: INFLUXDB_ADMIN_TOKEN # <-- This is the key within that secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"