name: Deploy API to Google Cloud

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK and gke-gcloud-auth-plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          cd api # Navigate to the api directory
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}
          docker build --push --no-cache \
            --file Dockerfile \
            --tag flamware/capiot-influxDB:$IMAGE_TAG \
            .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV # Make IMAGE_TAG available as an env var for subsequent steps

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_CREDENTIALS }}'

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: capiot-eu-cluster
          location: europe-west9
          project_id: awesome-vigil-454917-q7

      - name: Apply Kubernetes Deployment
        run: |
          # Option 1: Directly modify the YAML using sed before applying
          sed -i "s#image: flamware/capiot-influxDB:latest#image: flamware/capiot-influxDB:${{ env.IMAGE_TAG }}#g" kubernetes/api/influxdb-deployment.yaml
          kubectl apply -f kubernetes/api/influxdb-deployment.yaml
          kubectl apply -f kubernetes/api/influxdb-secrets.yaml
          kubectl apply -f kubernetes/api/influxdb-service.yaml
          echo "Kubernetes Deployment applied successfully with image tag: ${{ env.IMAGE_TAG }}"